nome = str(input('Digite seu nome completo:'))
print('Seu nome maiusculo é {}'.format(nome.upper()))
print('Seu nome minusculo é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome),nome.count('')))
print('Seu primeiro nome tem {}'.format(nome.find(' ')))
